### ISSUE TITLE
Kafka-manager can't see cluster

### ISSUE THREAD

**Issue by ilkertuna** [Yolean/kubernetes-kafka#252] opened 2019-03-25 09:12 UTC
Kafka-manager can't see our cluster, is it related the Kafka-manager version?
How can I connect my cluster?

![Screenshot from 2019-03-25 12-11-10](https://user-images.githubusercontent.com/7367514/54907714-3e435700-4ef7-11e9-94aa-7ff992f1c1b5.png)

**Comment by solsson** [comment] 2019-03-25 19:08
@ilkertuna Does #251 help?

**Comment by blinkeye** [comment] 2019-03-31 07:53
@ilkertuna: with the latest changes just fill in the `Cluster Name` with a name of your own and the `Cluster Zookeeper Hosts` with: 
```
zookeeper.kafka:2181
```

**Comment by blinkeye** [comment] 2019-04-01 15:29
@solsson : looks like a  duplicate of #244.

**Comment by solsson** [comment] 2019-04-02 02:26
Not sure you meant #444, but anyhow @ilkertuna I'll close this now after the Kafka Manager upgrade got bumped. Please re-test, and re-open if issues still surface.

**Closed by solsson** 2019-04-02 02:26 UTC
